# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0f56e15cbc3a2f6ff0e8eb78eac650a44f176776469ae1f8e24be3c04f255a48b0c8a07caf8d95c9b96891e2eb2c77ce5dad4cf3d2913cecda9b728d585a5e

test:
  secret_key_base: 4e4ebabd325d1b578c4b5c5cb414ce43b2e23e17f1e2b15a7a50403b0e8825df2ffd011a5778e9958e37b14766efc84b1fb19f554811a634254ee53530f22e27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
